hello_world_map_reduce:hello_world_map_reduce.c main.c hello_world_map_reduce.h
	gcc -o hello_world_map_reduce hello_world_map_reduce.c main.c -lpthread -Wall
run:
	./hello_world_map_reduce distances.txt

clean:
	rm hello_world_map_reduce
